version: "3"
services:
  app:
    build: .
    ports:
      - 5000:5000
    restart: unless-stopped
    devices:
      - /dev/gpiomem:/dev/gpiomem
    volumes:
      - db-data:/app/userInterface

volumes:
  db-data:
    driver: local
